import Head from "next/head";
import Navbar from "@/compenents/Navbar";
import Clock from "@/compenents/Clock";
import Photos from "@/compenents/Photos";
import Footer from "@/compenents/Footer";

export default function Photo() {
    return(
        <>
            <Head>
                <title>FOTO | ZECA</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link
                rel="icon"
                href="/wtt-favicon-black.ico"
                media="(prefers-color-scheme: light)"
                />
                <link
                rel="icon"
                href="/wtt-favicon-white.ico"
                media="(prefers-color-scheme: dark)"
                />
            </Head>

            <Navbar />
            <Clock />

            <Photos />

            <Footer />
        </>
    )
}