import Head from "next/head";
import Navbar from "@/compenents/Navbar";
import Clock from "@/compenents/Clock";
import Footer from "@/compenents/Footer";
import Video from "@/compenents/Video";

export default function Photo() {
    return(
        <>
            <Head>
                <title>VÍDEO | ZECA</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link
                rel="icon"
                href="/wtt-favicon-black.ico"
                media="(prefers-color-scheme: light)"
                />
                <link
                rel="icon"
                href="/wtt-favicon-white.ico"
                media="(prefers-color-scheme: dark)"
                />
            </Head>

            <Navbar />
            <Clock />

            <div className="main-content">
                <p>Não a nada para ver aqui. Por enquanto...</p>
            </div>

            {/* <Video /> */}

            <Footer />
        </>
    )
}